version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14-browsers # Use the Node.js Docker image

jobs:
  build:
    executor: node-executor
    steps:
      - checkout # Check out the code from your repository

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Start Server
          command: npm start

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
