name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CI_SERVER_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CI_SERVER_USER }}@${{ secrets.CI_SERVER_IP }} << 'EOF'
            cd cii-notification-server
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            docker ps -q --filter "ancestor=ci-noti:1.0" | xargs -r docker stop
            docker ps -a -q --filter "ancestor=ci-noti:1.0" | xargs -r docker rm
            docker build -t ci-noti:1.0 .
            docker run -d --env-file .env -p 3000:3000 ci-noti:1.0
          EOF
