name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CI_SERVER_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CI_SERVER_USER }}@${{ secrets.CI_SERVER_IP }} << 'EOF'
            cd ci-notification-server
            git pull origin main
            docker stop ci-server:1.0 || true
            docker rm ci-server:1.0 || true
            docker build -t ci-server:1.0 .
            docker run -d --env-file .env --name ci-server:1.0 -p 3000:3000 ci-server:1.0
          EOF
